---
abstract: 'Perl extension for libgsm'
author:
  - 'Alexander Frolov <froller@froller.net>'
build_requires:
  ExtUtils::MakeMaker: 6.63
  Test::Simple: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-GSM
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.04
